// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqRoLrG93DKZ6Ij9TnjUBvzim6NLDn97Q',
    appId: '1:316384541812:web:0b97e00ef79b197931a521',
    messagingSenderId: '316384541812',
    projectId: 'bookpanda-daf35',
    authDomain: 'bookpanda-daf35.firebaseapp.com',
    storageBucket: 'bookpanda-daf35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2grc2bzFO6y8XCVmY1I_8cYyPpkjhccM',
    appId: '1:316384541812:android:842f1782fd13dbd031a521',
    messagingSenderId: '316384541812',
    projectId: 'bookpanda-daf35',
    storageBucket: 'bookpanda-daf35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGeeQFSUQ4JIvXWwQUXpf-pjbWVxQdEg',
    appId: '1:316384541812:ios:9f2f7ede31f9c99331a521',
    messagingSenderId: '316384541812',
    projectId: 'bookpanda-daf35',
    storageBucket: 'bookpanda-daf35.appspot.com',
    iosClientId: '316384541812-m2g07hbgbmdc1g104qhop7c5q73ttf41.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginTest',
  );
}
